### ISSUE TITLE
Unable to change font in the middle of a paragraph

### ISSUE THREAD

**Issue by rpiazza** [trade-informatics/caracal#10]
I would like to change the font of one word in the middle of a paragraph, that is in a table cell.  Here is the code I wrote, but it seems to have no effect.

docx.font do
  name 'Courier New'
end

docx.style(id: 'UML', name: 'UML', font:'Courier New', size: 12 * 2)

       row[3] = 
          Caracal::Core::Models::TableCellModel.new do
            p do 
              text "The " 
              text e.name, style: 'UML'
              text " property "
              text e.documentation
            end
          end

I had previously tried something similar, with this code instead, but that didn't work either

text e.name, font: 'Courier New'

**Comment by jdugan-plia** [comment]
Syntactically, using a custom style with the `text` command is the right approach.  I'll set up a test and see if I can replicate.

**Comment by jdugan-plia** [comment]
Yep, this is definitely not working correctly.  I'll have to review the OOXML spec again to figure out what we're not doing correctly.  I'll respond here when I patch the library.  Today, if it's not too difficult to remedy.

**Comment by jdugan-plia** [comment]
I ran a few experiments this morning and, based on the results, I think we should change course here.  Syntactically, I don't think Caracal should support a `:style` parameter on the `text` command.  Applying styles to text runs in Word results in some pretty erratic behavior, and it seems pretty clear to me that Word strongly prefers for a paragraph to have a single style.  Any adjustments within the paragraph work fine when they're made on a property-by-property basis.  To wit:

If we do this:
```ruby
docx.p do
  text 'This line begins in the normal style '
  text 'and ends in a custom style', style: 'customStyle'
end
```
We get exactly what we expect.

However, as soon as we do something like this:
```ruby
docx.p do
  text 'This line begins in the normal style '
  text 'and switches to a custom style', style: 'customStyle'
  text 'and finishes back with the normal style.'
end
```
Then the entire line is reverted to normal style.

Similarly, if you type a sentence in Office365, then highlight one word, then apply a new style to the highlighted selection, what actually happens is Office365 applies the style to the entire paragraph.

SO.  I think we should stop accepting `:style` on `text` and instead accept `font`.  This seems more consistent with how MS editors handle intra-paragraph adjustments.  So, going forward, the correct syntax would be:
```ruby
docx.p do
  text 'This line begins in the normal style '
  text 'and switches to a different font', font: 'Courier New'
  text 'and finishes back with the normal style.'
end
```

I'll see if I can make the change this afternoon.

**Comment by jdugan-plia** [comment]
Latest release v0.3.0 should solve your issue using the syntax from the final example in the preceding comment.

```ruby
docx.p do
  text 'This line begins in the normal style '
  text 'and switches to a different font', font: 'Courier New'
  text 'and finishes back with the normal style.'
end
```

**Comment by rpiazza** [comment]
works great, you can close
