### ISSUE TITLE
How can i chance cellspacing & cellpadding table?

### ISSUE THREAD

**Issue by ticovidal** [trade-informatics/caracal#101]
How can i chance cellspacing & cellpadding table? All my tables are "fat".

**Comment by jdugan** [comment]
Looks like the documentation in the README is wrong.  

Table Cells have default margins--akin to cellpadding in HTML--of 100 twips.  Margins in all directions are configurable as described in the README.  I'll fix the documentation shortly. 

To create cellspacing, I believe you could declare a table border of the desired size and set the border color to the background color.
