### ISSUE TITLE
Document is corrupted

### ISSUE THREAD

**Issue by spiffistan** [trade-informatics/caracal#12]
When opening the document in word it is reported as corrupted. The automatic recovery dialog is able to repair it, but it reports an error with "Styles 1".

I've tried both with contents and empty documents.

As an aside; when unzipping the document with 'unzip', I get the following warning:
```
test % unzip 10.docx 
Archive:  10.docx
warning [10.docx]:  34710 extra bytes at beginning or within zipfile
  (attempting to process anyway)
```

I did try to downgrade RubyZip from 1.1.7 to 1.1.0, with no success.

Ruby 2.2.2, Rails 4.2, Caracal 1.3.0

**Comment by jdugan-plia** [comment]
Sorry, I was out of the country last week.  I'll try to help with your two issues today.  Caracal defers all zipping logic to RubyZip, so I doubt very much this is a Caracal issue per se.  I'll try to recreate using your specified stack.

What setup are you using? OSX, Linux, Windows?  We had an issue recently from a user who experienced a bug with RubyZip on a Windows server.  I've never had an issue with this on OSX or Linux.

**Comment by spiffistan** [comment]
OSX Yosemite in development, and ubuntu latest stable in production. Both versions report the error.

**Comment by jdugan-plia** [comment]
That's the same as me, and all my documents open fine.  Which version of Word are you using to view the documents?

**Comment by spiffistan** [comment]
I've tried with both MS Word 2013 on windows and Word for Mac Beta 2015.

**Comment by jdugan-plia** [comment]
Huh.  We've tested the library on a number of different versions of the software.  I thought MS Word 2013 was one of them, but there are so many versions of Word, it's hard to say.  I know it loads on Office365 and every 2010+ version we've tried.  You'd think if it uploads to Office365, it'd be compatible with all relatively recent versions, but maybe not.  

I'll look at the gist tomorrow and see if anything jumps out at me.

**Comment by spiffistan** [comment]
I did a little digging and found this issue in Pandoc which may or may not shine some light on it:

https://github.com/jgm/pandoc/issues/414

**Comment by jdugan-plia** [comment]
My first instinct is to look at what jgm kept asking for--the xml we create vs. the xml Word creates when it "repairs" the document.

I'm guessing your gist is from the repaired version?  If so, can you also post the contents of all the other files to your gist?  I'm hopeful that we can just change a few namespaces and everything will be fine.

**Comment by spiffistan** [comment]
It was from the unrepaired version. I did a shallow comparison now:

```
unrepaired.docx: 30944 bytes
unrepaired % unzip unrepaired.docx 
Archive:  unrepaired.docx
warning [unrepaired.docx]:  24952 extra bytes at beginning or within zipfile

repaired.docx: 11692 bytes
repaired % unzip repaired.docx 
Archive:  repaired.docx
(no warning)
```

There are significant changes to the XML as well. I'll post the changes sometime later today.

**Comment by spiffistan** [comment]
Here is a gist with the XML from the repaired document: https://gist.github.com/spiffistan/0016ace92833f766225b

**Comment by spiffistan** [comment]
Had the chance to look at this yet? Perhaps we could compare the XML from our respective empty documents...

**Comment by jdugan** [comment]
Sorry, I've been absolutely slammed at work the past few weeks.  I apologize.  I *swear* I have not forgotten about this.  I'm hoping to get it on my agenda this week.

**Comment by spiffistan** [comment]
No worries. I'll go another round on this myself to see if I can figure something out as well.

**Comment by spiffistan** [comment]
FYI: I haven't been able to find out anything. Have you been able to look at it?

**Comment by jdugan** [comment]
I still haven't.  I'm really sorry.  If you don't mind, you might try an experiment for me.  The way I built Caracal was pretty naive.  I generated a Google document that contained all the functionality I considered essential, saved it as a .docx, and then unzipped it.  Most of the OOXML comes directly from Google's output.  I wonder if you followed those steps if:

1. The resulting .docx would open in your version of Word; and, if so,
2. How the Google Doc OOXML differs from Caracal's.

There might be some simple compatibility declarations we could make to fix the problem at the root.

**Comment by theocapdet** [comment]
Hello,

I have the same problem.
I just install the gem and i just put in my controller :

Caracal::Document.save 'example.docx' do |docx|
      docx.h1 'Page 1 Header'
end

The document is create but is corrupted. Do I use the gem correctly ?

**Comment by jdugan** [comment]
@theocapdet Yes, you did.  (Though, you might want to use caracal-rails to simplify usage in Rails.  I published the example Rails project I use for generating test documents yesterday.  You might view that for an example of what I would consider idiomatic Rails usage. https://github.com/trade-informatics/caracal-example)

Regarding the corruption issue, welcome to the maddening world of Microsoft product versions!  The library works perfectly in all the MSWord version to which I have personal access, but apparently every version available.  I had hoped achieving compliance in Office365 would put the library's output in good stead with all current versions of Word, but clearly that is not so.

Which version(s) are you using?

**Comment by theocapdet** [comment]
@jdugan  Thank you for your answer.
I try with open it with :
- "Libre office, Version: 4.4.4.3"
- "Microsoft Word 2010 in Microsoft office Professional plus"

**Comment by jdugan** [comment]
It definitely will not work with LibreOffice/OpenOffice.  Confusingly, while LO/OO are written to a specification named OOXML, this is a different OOXML than the OOXML that underwrites MSWord.  Despite using the same acronym, the specifications differ considerably.  So, for now, LO/OO is considered outside the scope of Caracal's intent--it is a library for generating MSWord documents.

Having written that, Caracal documents do generally open in OpenOffice 4.0 for me, though formatting is not point-perfect and not all features are supported.  I'm downloading 4.1 now to check compatibility there.

I'm a little frustrated by Word version support.  My coworkers have been able to open the documents in MSWord 2010 for Mac and I thought others had opened it on MSWord 2010 for Windows.  I'll need to double check the latter, I guess.  Would you mind trying the experiment I proposed above?  Generating an equivalent Google doc, saving as docx, and opening in your version of MSWord?

**Comment by jdugan** [comment]
Huh.  Interestingly, the document generated by the example project opens perfectly fine in LibreOffice 4.4.4.3, which appears to have a considerably better OOXML-to-OOXML converter than OpenOffice.  The document in LibreOffice looks pretty much exactly like what I would expect to see in MSWord.

**Comment by theocapdet** [comment]
I try "caracal-rails" same problem the caracal.docx is created but corrupted.
Maybe because I use ruby 1.9.3 or rails 4.2.1 ?

In controller :
format.docx { headers["Content-Disposition"] = "attachment; filename=\"caracal.docx\"" }

In my routes : 
resources :cvs,only: :show, format: 'docx'

In the cvs/show.docx.caracal I put the example code

I Download the docx with : 
link_to 'WORD', cv_path(@cvmodif, :format => 'docx')

Does I have forgot something or maybe I need to upgrade version of rails or ruby?

**Comment by jdugan** [comment]
Nope, definitely works fine with those versions of ruby and rails.  If you clone the https://github.com/trade-informatics/caracal-example project, you'll see that it references Rails 4.2.1.  I just ran that using ruby-1.9.3-p194 and everything opened fine.

Try this: Take the file you just created and change its extension from docx to zip.  Then extract the compressed file.  Does that work?  Do you see a directory structure of XML files?  If your development machine is a PC, there is a confirmed issue with RubyZip that might be your main problem.  Please see the discussion at the bottom of this issue: https://github.com/trade-informatics/caracal/issues/8.  AFAIK, RubyZip works fine on any *nix OS.  It certainly works on Ubuntu and OSX.

**Comment by theocapdet** [comment]
OK that work you are my hero  !!!!!! Thank you for your precious help !
It doesn't work because I work on windows. I install a VM with ubuntu, like you say, and that Work perfectly !

Thank you again for your work. :)

**Comment by spiffistan** [comment]
@jdugan Alright, I'll have a look and compare versions tonight!

**Comment by spiffistan** [comment]
Here's a starting point, a diff between an empty document.xml saved from word and saved from google docs: 

https://gist.github.com/spiffistan/72f56edd019e104eceb9

green = google docs version

**Comment by spiffistan** [comment]
And here's styles.xml:

https://gist.github.com/spiffistan/da36d4ebd59f21058899

green = google docs version

**Comment by spiffistan** [comment]
By chance my colleague opened the docx file in sublime...and lo, a full html file. Unzipping the docx still works...but the problem has been including the layout when rendering. 

Doing: 
```ruby
format.docx { render layout: false }
```

Solves the problem. D'oh!

Thanks regardless!
