### ISSUE TITLE
Is there a way to highlight ?

### ISSUE THREAD

**Issue by theocapdet** [trade-informatics/caracal#14]
Hello,
First, thank you form your work it's amazing !

I want to know if there is a way to hightlight text. I mean like the <span> in HTML. Moreover this function is already developped in Word.

Thank you in advance :)

**Comment by jdugan** [comment]
First, thanks for the kind words.  It's always deeply gratifying to hear that the library is useful to someone else.

There is not currently a way to highlight, but I don't think that would be difficult to add.  Let me do some research and get back to you.

**Comment by jdugan** [comment]
Alright, that was much easier than I imagined.  

I added text highlight via an attribute `:bgcolor` that can used with the following commands: `text`, `p`, `link`, and `li`.  The attribute takes a six-character RGB value.  It worked okay for me in my tests with Office365.  Let me know how it goes!

For example:
```ruby
docx.p do
  text 'This is a sentence with a '
  text 'highlighted run', bgcolor: 'ff3300'
  text ' within the text.'
end
```
