### ISSUE TITLE
undefined method `new' for :TableCellModel:Symbol

### ISSUE THREAD

**Issue by theocapdet** [trade-informatics/caracal#15]
Hello,

There is an issue with the table cell.
When I create a cell separately I have this error : 
     undefined method `new' for :TableCellModel:Symbol

I create a cell like that :

c1 = Caracal::Core::Models:TableCellModel.new do
    docx.h1 'hello'
end

Do you know what is the problem?

Thank in advance.

**Comment by jdugan-plia** [comment]
You're missing a colon between Models and TableCellModel.
