### ISSUE TITLE
ActionView::Template::Error (undefined method `image_url')

### ISSUE THREAD

**Issue by theocapdet** [trade-informatics/caracal#16]
Hello,
It seem the method 'image_url' is not implemented in a cell table like in your example.

when I put like in your example:

c1 = Caracal::Core::Models::TableCellModel.new do
  img image_url('http://sweetclipart.com/multisite/sweetclipart/files/big_gold_star.png'), width: 120, height: 60
end

docx.table [[c1]] do
    cell_style cols[0], width: 120
end

It return me this error : 
 ActionView::Template::Error (undefined method `image_url' for #<Caracal::Core::Models::TableCellModel:0x007f5f53f465c8>):

when I simply put :
docx.img image_url('http://sweetclipart.com/multisite/sweetclipart/files/big_gold_star.png'), width: 120, height: 60
My image is printed correctly.

I don't know if it's an issue or anything else?

PS : I have two column in my table but I have simplified to one.

**Comment by jdugan-plia** [comment]
The `image_url` calls in my examples are referencing the Rails helper function that converts an image name to a full path through the asset pipeline.  It's not part of Caracal per se.

Here, you already have a fully-qualified reference to the image url, so you should be able to skip the image_url call altogether and just pass the url string into Caracal's img method.

```ruby
c1 = Caracal::Core::Models::TableCellModel.new do
  img 'http://sweetclipart.com/multisite/sweetclipart/files/big_gold_star.png', width: 120, height: 60
end
```

If you need Rails helpers to generate Caracal arguments, you can achieve that by building the values within the document context and then using those variables within the cell context.  Something akin to how you might share a reference with an anonymous function in Javascript:

```ruby
my_url = image_url('star.png')
c1 = Caracal::Core::Models::TableCellModel.new do
  img my_url, width: 120, height: 60
end
```

**Comment by jdugan** [comment]
I'm going to assume that answered your question and close this one. :)
