### ISSUE TITLE
Word found unreadable content

### ISSUE THREAD

**Issue by adamreisnz** [trade-informatics/caracal#162]
Hi, is there anything that can be done to stop this warning from showing up for DOCX files generated by Caracal?

![image](https://github.com/user-attachments/assets/10ec5eb9-5df0-4396-b6ce-a7204f23f49b)

It opens fine in Pages, Google Docs, without warning.
But in MS Word it shows this warning, and renders fine if you select Yes.

**Comment by janlesko** [comment]
Same issue here, but only when I include images in the file.

**Comment by adamreisnz** [comment]
I think in the end this turned out to be because the extension was missing from the filename.
