### ISSUE TITLE
how to merge table cell.

### ISSUE THREAD

**Issue by boostbob** [trade-informatics/caracal#19]
Is there a way to do like the `css #table#td#colspan` prop?

**Comment by jdugan** [comment]
Not right now.  You can accomplish this with nested tables (though that is admittedly clumsy).  

Caracal was built for a specific project and that project didn't happen to need merged cells.  It's still very much an MVP.  I do accept pull requests, though.  If you're willing to research the OOXML and you provide a patch that follows the library's structure and style, I'll accept it with gratitude.
