### ISSUE TITLE
How can i create a complex table like this

### ISSUE THREAD

**Issue by sunlixin-conac** [trade-informatics/caracal#21]
Hi,
    First, thanks for your great work. It is very useful for me, i like it very much.
    Now, i want to create a table likes this, but there are some questions for me.
![qq 20151209181636](https://cloud.githubusercontent.com/assets/6658519/11682628/12ee1216-9ea1-11e5-9f89-89c475a72a31.png)
    My question is: 
    1, How can i insert a picture in a cell. 
    2, How can i split a cell like row 2
many thanks

**Comment by matwej** [comment]
1. it is actually mentioned in the readme near the bottom
"Table Cells

If your table contains more complex data (multiple paragraphs, images, lists, etc.), you will probably want to instantiate your TableCellModel instances directly. With the exception of page breaks, table cells can contain anything the document can contain, including another table."
2. probably as mentioned above, create inner table in that cell

**Comment by jdugan** [comment]
Yes, that's correct, @matwej.  For now, Caracal does not support merge cells.  As noted in [Issue 19](https://github.com/trade-informatics/caracal/issues/19), pull requests are welcome.
