### ISSUE TITLE
How to insert a page break after each li?

### ISSUE THREAD

**Issue by Priya101** [trade-informatics/caracal#23]
I have code like below:-
docx.ol do
li 'first'
li 'second'
end
I need to insert a page break after each li.
I tried with docx.page after li but that didn't worked.

**Comment by jdugan** [comment]
I just created v1.0.3 of Carcal to allow this behavior.  To get the result you want, you will need to specify the `li` directives in their expanded, block form:

```ruby
docx.ol do
  li do
    text 'This is the first list item.'
    page
  end
  li do
    text 'This is the second list item.'
    page
  end
  ...
end
```

Again, because the `li` model extends the `p` model, you can use any paragraph directive inside a list item.  Good luck!
