### ISSUE TITLE
Pass through option?

### ISSUE THREAD

**Issue by davidtolsma** [trade-informatics/caracal#25]
I'm working on taking a text area that renders html, and want to pass it through to my docx file. I can't seem to find a way to render my converted html text that i've already converted to docx format (example: <w:br/>) and have it show up in the file.

Is there a pass through option that takes takes docx formatted string and drops it into the document? or is there another option available?

**Comment by jdugan** [comment]
No, there's nothing like that right now.  To continue the HTML syntax theme, I wonder if it might make sense to implement this with a new directive named `pre`?

Maybe create a preformatted model that simply accepts text and a sort of do-nothing document rendering function?

**Comment by davidtolsma** [comment]
That would be good. I was thinking the similar. I'll give it a shot and see what i can get accomplished.

**Comment by jdugan** [comment]
Hey, I doubt you care about this, but we implemented something like this recently via an `iframe` directive.  I'm going to close the issue.

**Comment by davidtolsma** [comment]
thanks
