### ISSUE TITLE
How to use li with list type none ?

### ISSUE THREAD

**Issue by Ramyani** [trade-informatics/caracal#26]
I have following lines:
docx.ul do 
  li 'Text1'
  li 'Text2' 
end

I don't want list items to be marked with any bullets, numbers or letters.

**Comment by jdugan** [comment]
If you want all unordered list to have this appearance, the best choice is to alter the default list styles applied to the document using the `list_style` directive.  You can get an overview in the [README](https://github.com/trade-informatics/caracal/blob/master/README.md#list-styles).  If you'd like to see the default values used by the document as a reference, you can do so [here](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/core/list_styles.rb#L32).  I believe the `format` value you want is 'none', but you can research the OOXML tags used by the [renderer](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/renderers/numbering_renderer.rb#L19) by googling `ooxml` and the tag in question.

If you only want this appearance for a single list, it might actually be easier to implement your unstyled list as a borderless table.  (Tables are also covered in the README.)
