### ISSUE TITLE
dependency on tilt conflict with sass-rails

### ISSUE THREAD

**Issue by ohenrik** [trade-informatics/caracal#28]
I'm getting this when i try to bundle caracal:
```
Bundler could not find compatible versions for gem "tilt":
  In Gemfile:
    caracal (>= 0) ruby depends on
      tilt (~> 1.4) ruby

    sass-rails (~> 5.0) ruby depends on
      tilt (2.0.1)
```

My temporary solution was to add `gem 'tilt', '~> 1.4'` to my gem file and then `bundle update tilt`, but it might be better if caracal could handle tilt 2.0 and above?

**Comment by jdugan** [comment]
You're right, of course.  That would be better.  Caracal has a super naive implementation of Tilt--really just enough to help a program understand how to map the *.docx.caracal extension to the right renderer.  I suspect it'll work just fine in Tilt 2.0.

I'll change the dependency declaration and post an update to github, which you can use to test your project.  If that works okay, I'll post a patch revision to rubygems.  Should just take a few minutes.

**Comment by jdugan** [comment]
Nevermind.  I realized I could (and should) test the `caracal` change using the `caracal-example` repo.  Everything worked totally fine in Tilt 2.0.  There's a new version of `caracal` in rubygems (v1.0.4) that should pass your bundle step.  I also updated the code in the example repo.

Takk!

**Comment by ohenrik** [comment]
Perfect! Updated my gems today and it works perfectly! :) Takk!
