### ISSUE TITLE
How to display image with original size

### ISSUE THREAD

**Issue by Ramyani** [trade-informatics/caracal#32]
Is there any way to display the image with it's original height and width ?
eg:
`docx.img image_url('https://www.example.com/logo.png')`

Currently we have to always pass the height and width options manually, otherwise it throws error.
```Caracal::Errors::InvalidModelError: Images require an URL and positive size/margin values.```

Thanks!

**Comment by jdugan** [comment]
No, as your testing indicates, this is a requirement of Caracal.  AFAIK, Word documents--like PDF files--require explicit image dimensions in order for them to print properly.

There are a variety of ruby libraries that can dynamically calculate image dimensions for you.  I'd suggest you take that route.  Image interpretation/inspection is something I consider to be outside the scope of Caracal's responsibilities.
