### ISSUE TITLE
Is there any way to display text with Rich Text Format?

### ISSUE THREAD

**Issue by Ramyani** [trade-informatics/caracal#33]
Is there any way to display text with Rich Text Format with proper stylings?
eg. 

```"<em><strong><span style=\"color:#0000FF\">Hello</span></strong> <strong><span style=\"color:#008000\">World</span></strong></em>"```

Thanks!

**Comment by jdugan** [comment]
If you're asking if you can set the color, weight, and style of text, then yes, certainly that is possible.  The README covers both creating your own style classes for styles you use repeatedly and applying one-off styles to paragraphs and text blocks.  There are also several examples of this kind of thing in the [Caracal example repo](https://github.com/trade-informatics/caracal-example).

If you're asking if you can paste HTML snippets directly into the document, then the answer is no, you cannot do that.
