### ISSUE TITLE
Variables to Model

### ISSUE THREAD

**Issue by tsolar** [trade-informatics/caracal#35]
I want to use variables in a TableCellModel. Is it possible to do something like this?

```
c2 = Caracal::Core::Models::TableCellModel.new margins: { top: 0, bottom: 100, left: 0, right: 200 } do
  ul do
    @minisite_publication.course.work_flow.each do |stage|
      li "#{stage[:name]}"
    end
  end
end
```

I am getting ```undefined method `course' for nil:NilClass```. So, `@minisite_publication` variable is nil,  I don't know how to pass it.

**Comment by jdugan** [comment]
I believe you have the same lexical context issue discussed in this [closed issue](https://github.com/trade-informatics/caracal/issues/29).  Let me know if that helps/makes sense.

**Comment by tsolar** [comment]
I've just declared `minisite_publication = @minisite_publication` before it and remove the `@` from the variable inside the `ul` and it worked like a charm!

Thank you very much!
