### ISSUE TITLE
Carriage returns

### ISSUE THREAD

**Issue by omaralkaisy** [trade-informatics/caracal#37]
Hi

I have a text area with carriage returns. However these do not show on the caracal output. How can I get the text area to be displayed as entered pls including carriage returns?

Thanks!

Omar

**Comment by jdugan** [comment]
Hi, Omar.

Off the top of my head I think the approach I would try would be to use ruby to split your text string by line feeds/carriage returns and use that local array variable to issue `p` and `br` commands (or `text` and `br` commands within a `p` block).  Something roughly analogous to how the `simple_format` function in Rails works.

This might also be a good case for you to make some kind of utility class or view model, if the translation I described above is something you need to do repeatedly in your document view.
