### ISSUE TITLE
Breaks and multiple paragraphs in table cells

### ISSUE THREAD

**Issue by Chillibear** [trade-informatics/caracal#38]
I've not fully investigated yet, but it appears there is a problem with line breaks in table cells.  The following code illustrates this:

```
#!/usr/bin/env ruby
#encoding: UTF-8

require 'rubygems'
require 'caracal'

Caracal::Document.save('table-cell-br-test.docx') do |docx|

  # Only the second line of text shows
  broken_cell_br = Caracal::Core::Models::TableCellModel.new do |c|
    c.p do |para| 
      para.text'First line'
      para.br
      para.text'Second line'
    end
  end

  # Both pieces of text show
  working_cell = Caracal::Core::Models::TableCellModel.new do |c|
    c.p do |para| 
      para.text'First line '
      para.text'Second line'
    end
  end

  # Only the second paragraph shows
  broken_cell_para = Caracal::Core::Models::TableCellModel.new do |c|
    c.p "first para"
    c.p "second para"
  end  

  docx.table [ [broken_cell_br, working_cell, broken_cell_para] ] do
  end
end
```

When I've tried putting a line break in a paragraph within a table cell I only see part of the output in the rendered `.docx`.  The data is present in the `.docx` however.  If I do an _autoformat_ of the resulting table from within MS Word (2008 - Mac) I see all the expected text with the expected line breaks.

I'll try to investigate further, but thought I'd at least open a ticket in case I'm missing something obvious.

**Comment by jdugan** [comment]
Sorry for the delayed response.  This is a one-man community for the most part, and this one man was moving his family across the country last month.

The short version here is Caracal has never been tested against that version of Word.  Caracal was designed for Word 2010, 2013, and Office365.  Word 2008 for Mac arrived in the earlier days of the .docx format, so I suspect it has problematic support for .docx files in general.

While .docx was supported in Word 2007 and Word 2008 for Mac, the OOXML varies pretty widely from what is expected in 2010 and 2013 (which are quite similar to each other).  Given the age of 2007 and 2008, we made the decision not to support anything older than 2010 when Caracal was originally designed and built.

FWIW, your Caracal syntax looks fine to me.  

Caracal is, in effect, an exercise in reverse-engineering XML output.  You might try building the simplest version of the feature in Word and saving that document.  Then changing the extension to .zip and extracting the file.  From there, you can inspect the XML Word produced and see if there's some simple change or addition you could make to make the feature compatible with your version without wrecking 201/2013 support.

**Comment by Chillibear** [comment]
My apologies, I quite missed the version notes in the main readme.  Glad the example looks correct, I'll  see if I can test in Libreoffice or something to confirm it's just my ancient copy.
