### ISSUE TITLE
Table with no borders not working

### ISSUE THREAD

**Issue by danielsampete** [trade-informatics/caracal#39]
```
docx.table [['Header 1','Header 2'],['Cell 1', 'Cell 2']] do
  border_size    0          # sets the border width. defaults to 0. units in twips.
end

```

**Comment by jdugan** [comment]
I know it's not what you're asking, but the default table border size is already 0.  You needn't specify anything to get that behavior.

OOXML interpretation can vary widely between versions of Word.  It's nearly impossible for me to help debug these kinds of issues without knowing the version being used in your development environment.  Even then, it's not always possible for me to help beyond describing how I approach these formatting issues.  (I can't own every permutation of Word and Windows versions.)

What I can do is assure you that this feature works for all the versions of Word I've ever tested.  What I normally recommend is folks first run the [caracal-example](https://github.com/trade-informatics/caracal-example) project, which is my attempt to demonstrate the canonical way of implementing caracal features.  It also shows a working version of nearly every feature Caracal supports.  So, if something in the example project is broken in your version of Word, you have, in effect, uncovered an OOXML variance between versions of Word that Caracal doesn't yet know about.
