### ISSUE TITLE
README example document should actually run

### ISSUE THREAD

**Issue by fatuhoku** [trade-informatics/caracal#43]
Great library! The first thing I tried to do was to copy and paste the following snippet to try caracal for myself:

![screen shot 2016-06-10 at 11 59 42](https://cloud.githubusercontent.com/assets/430233/15962427/de8224a2-2f02-11e6-9e81-4ff45acb5e15.png)

It didn't work. Two things stopped me from getting this really simple example to work:

 - `@mydata`. I had no idea what it should look like
 - `/Users/fushunpoon/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/open-uri.rb:358:in `open_http': 404 Not Found (OpenURI::HTTPError)` — I presume this is because of the network image.

**Comment by fatuhoku** [comment]
Thanks for your response. Of course, I'll exercise patience.

**calms**

Caracal's cool — I don't mean to inundate you with issues.

They're intended as much to be a question, or a suggestion for improvement than 'something wrong' with the project. I've seen other projects where questions and suggestions are welcome.

Thanks for pointing me to the example project. I'm not actually using Rails. I just want to see the code that generates the docx and didn't know where to look.

**Comment by jdugan** [comment]
Sure, I'm always thrilled by user interest in the library.  I don't mean to kill your enthusiasm. :)

I was really just trying to suggest that you might make more progress with Caracal by slowing down a bit and learning how it does what it does.  You're asking enough questions that I think you'd benefit from reviewing the library's architecture and intent more closely.  I think if you did that, you'd be able to answer most of these questions on your own by reviewing the source code or interrogating the library through the example project.
