### ISSUE TITLE
Paragraph bold true doesn't seem to work while styles work

### ISSUE THREAD

**Issue by fatuhoku** [trade-informatics/caracal#47]
I have a tabel cell that looks like this:

```ruby
docx.style { id 'NormalBold'; name 'NormalBold'; font 'Arial'; bold true }
```

```ruby
cell = Caracal::Core::Models::TableCellModel.new do
  p('This is bold') { style 'NormalBold' }
  p('This is not bold') { bold true }
end
```

i.e the the style works, but setting bold on the paragraph does not.

**Comment by jdugan** [comment]
Yep, this is a bug.  

The `paragraph` model isn't handling block attributes correctly.  As a temporary workaround, you can simply convert to the alternate syntax and provide your configurations via options, like so:

```ruby
  p 'This is bold', bold: true
```

I'll post a correction later today.

**Comment by jdugan** [comment]
Version 1.0.6 of Caracal fixes this issue.  Syntax flexibility is now restored for paragraphs.
