### ISSUE TITLE
Borders around individual table cells

### ISSUE THREAD

**Issue by fatuhoku** [trade-informatics/caracal#48]
Is this possible?

**Comment by jdugan** [comment]
It is, but you'd need to do it with nested tables.  Right now, borders can only be specified on tables, not on table cells.

I'm sure it's possible to do this in Word, but it would require a new feature.  It nested tables are to onerous for your use case, you're welcome to make a pull request to add borders to table cells.  There's information at the bottom of the README that describes how to work on new features.
