### ISSUE TITLE
Adding a Footer

### ISSUE THREAD

**Issue by ardavis** [trade-informatics/caracal#51]
How can I go about adding a static footer to each page, such as a copyright? 

I see that you have the ability to add page numbers, I was wondering if you had something similar for content?

**Comment by jdugan** [comment]
Not currently.  Caracal was built for a specific project, so it's feature set is largely a comment on that project's particular requirements.  Essentially, it's a kind of MVP.

I don't know how to add arbitrary content to a footer off the top of my head, but I suspect it's a tractable problem.  There's a description of my amazingly sophisticated reverse engineering process in this [README section](https://github.com/trade-informatics/caracal#how-to-work-on-a-problem).

The source code follows a fairly rigid personal style, which I use intentionally to help other folks get their bearings in the code base.  I think if you track the implementation of page numbering through from DSL to model to renderer, you'll find a good framework within to work.  If you get stumped in the process, please reach out and I'll try to help you get unstuck.

**Comment by ardavis** [comment]
@jdugan Thanks much for the quick response. I'll take a look and see if I can figure it out in my free time.
