### ISSUE TITLE
Possible to use dynamic images in tables?

### ISSUE THREAD

**Issue by JuliaDahm** [trade-informatics/caracal#53]
I've been building out a table in order to float some elements next to each other. In row5 I'm trying to display a model object's image: 

`row1 = ['Sounds Like']
row2 = ["#{@customer.sounds_like1}"]
row3 = ["#{@customer.sounds_like2}"]
row4 = ["#{@customer.sounds_like3}"]
row5 = [@customer.live_photo]
docx.table [row1.dup, row2.dup, row3.dup, row4.dup, row5.dup] do
  cell_style rows[0],  bold: true, width: 100
  cell_style rows,     align: 'center', width: 100
end`

Which just outputs the photo's path: 

/system/customers/live_photos/000/000/015/original/o-FKA-TWIGS-facebook.jpg?1478194510
 
Not sure what I'm doing wrong here. Also, I have the Paperclip gem handling the images (incase that helps). 

Thanks!

**Comment by istiaqiut** [comment]
Hello @JuliaDahm,
How did you solve the problem?
Thanks.

**Comment by istiaqiut** [comment]
Hi again @JuliaDahm ,
Have you created dynamic rows?
Thanks
