### ISSUE TITLE
Compability mode

### ISSUE THREAD

**Issue by arnaskro** [trade-informatics/caracal#56]
Hello,
I'm working on generating an invoice using 'caracal'. Everything seems fine, except when it gets generated and I open it the bottom borders of the tables are not showing. Well they are showing when the zoom level is above 100%, but when I try to print them out they are not showing again.. 

Perhaps it somehow related to being in "compatibility mode". Because when I convert it out of compatibility mode using Word, the issue is gone.

My first thought was that is was only me, but then I tried generating tables with different templates and tried opening them on another PC.. The result was that the bottom borders were still not showing on some of the tables, but as I have mentioned, when I convert them, then everything is fine.

Any thoughts on this?

**Comment by jdugan** [comment]
I've never seen this particular behavior, but as I'm fond of writing in these conversations, welcome to the wonderful world of OOXML. :)  Each permutation of Windows/OSX and Word seems to have its own quirks.  Out of curiosity, which OS and which version of Word are you running?

I'd be curious to know if you can resolve your issue by removing the `w:compat` node from the output.  You could do this either by extracting your caracal output, editing the XML, and rezipping it as a `docx` file; or you could fork the library, remove the Nokogiri command that adds the node to the output, and then recreate your file.

If that worked, we could maybe add a new directive to the DSL to tell the document renderer to add/ignore the w:compat node.  Caracal would render in compat mode by default, but the DSL would let you override that, if desired.
