### ISSUE TITLE
Want to ask

### ISSUE THREAD

**Issue by ariawanzero** [trade-informatics/caracal#59]
Can you make ul li nested in table column becasue i'm keep getting error when try to iterate from data model in table and can this gem generate page header beacause i want to give image logo in my docx header?

**Comment by jdugan** [comment]
Hi, thanks for the questions.  As a point of order, it's generally advisable to limit an issue to a single request.  If you ask about two separate things in the same issue, it's difficult to track the status and it makes it harder for others to find answers to their questions in the archive.

Concerning the list, TableCell should accept virtually any Caracal directive.  If you can provide a gist or inline ruby in a follow-up comment so I can see exactly what you're trying to do, maybe I can help you figure out what's going wrong and where.

Concerning the headers, please see [Issue 24](https://github.com/trade-informatics/caracal/issues/24).
