### ISSUE TITLE
How can i add image inside a table?

### ISSUE THREAD

**Issue by towonzhou** [trade-informatics/caracal#66]
```
row = docx.img(image_url('/default.png'), width: 300, height: 200, align: 'right')
docx.table [row], border_size: 2 do
  cell_style rows[0], align: :left
end
```
is wrong

**Comment by jdugan** [comment]
Agreed. :)  

Two things:

1.  The data element provided to a table is an array or arrays (i.e., a spreadsheet of data), not a simple array.
2.  The values in the data variable can only things which are TableCell model-ish.  Here, I recommend you explicitly wrap your image call in a TableCell model and pass in the table cell model as the data element.

Something like the following should work:
```ruby
myUrl = image_url('/default.png')
cell  = Caracal::Core::Models::TableCellModel.new do
  img(myUrl, width: 300, height: 200, align: 'right')
end
docx.table [[cell]] do
  ...
end

**Comment by towonzhou** [comment]
@jdugan Thank you!!!
