### ISSUE TITLE
Usage without blocks

### ISSUE THREAD

**Issue by ViktorKopychko** [trade-informatics/caracal#72]
Hello,
is there a possibility to generate docx file like so:

`docx = Caracal::Document.new('file.docx')`
`docx.h1("some text")`
`docx.save_file # some fake method`

rather than using default block construct:

`Caracal::Document.save('file.docx')) do |docx|`
`docx.h1("some text")`
`end`

**Comment by ysbaddaden** [comment]
You may:

```ruby
filename = "file.docx"
docx = Caracal::Document.new(filename)
buffer = docx.render
File.write(filename, buffer.string)
```

**Comment by ViktorKopychko** [comment]
Thanks!
