### ISSUE TITLE
How to remove default spacing between tables

### ISSUE THREAD

**Issue by mlabhinav** [trade-informatics/caracal#75]
hey,
is there a way to remove space between tables?. i just tried to remove space between tables, but in this caracal documentation i found nothing that can help  me on this. 
please help me on this.

**Comment by jdugan** [comment]
There's a PR available right now that purports to handle the issue.  I haven't had time to review and integrate the change yet, but if you need an immediate solution, I'd peg bundler to that branch for the short term.  At least one other user felt the PR was helpful.

I'll have time in December to catch up on the various PRs that have been submitted.  There should be a new official release in the next few weeks.

**Comment by mlabhinav** [comment]
thank you for your update, we can wait till December.

**Comment by istiaqiut** [comment]
Hi John,
We are waiting for your official release. It will be a great help if you can release this within a week.
Thanks.

**Comment by jdugan** [comment]
That's definitely not going to happen.  I won't have time for Caracal until later this month when I have time off for Christmas/New Year's.

**Comment by jdugan** [comment]
This is fixed in Release v1.4.0.  Table spacing must now be handled explicitly.
