### ISSUE TITLE
How to give columns name for tables

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#76]
I need to give columns name. It is better if you suggest a  way

I have tried this-
row1 = ['Key', 'Value']
row2 = ['Key 1', 'Value 1']
row3 = ['Key 2', 'Value 2']
row4 = ['Key 3', 'Value 3']

docx.table [row1.dup, row2.dup, row3.dup, row4.dup], border_size: 4 do
  cell_style rows[0],    bold: true,   background: '3366cc', color: 'ffffff'
  cell_style rows[-1],   bold: true,   background: 'dddddd'
  cell_style cells[5],   italic: true, color: 'cc0000'
  cell_style cols[0],    width: 6000
  cell_style cells,      size: 18, margins: { top: 100, bottom: 0, left: 100, right: 100 }
end

Here I want my columns name Key, Key 1, Key 2, Key 3.

**Comment by jdugan** [comment]
If I understand your question (and I'm not at all sure I do), it sounds like you just inverted the data.  Each element in the data array is a **row**.  So, if the first row would, in your example, need to contain all the column headers, since the header is the first row.

There is no fundamental difference in Caracal between a header row and a data row.  Everything is just a row.  Headers are created via different styling--that's it.

(I'm closing this issue because it isn't really a Caracal issue as much as your misunderstanding of the syntax.)

**Comment by istiaqiut** [comment]
Hi @jdugan ,
I got that.
Is there any way to create rows dynamically?
Thanks.

**Comment by jdugan** [comment]
Again, I'm a bit confused by the question.  Everything in Caracal is dynamic.  Every element on the document is defined by passing custom data to Caracal functions.  Tables are no different.

If your cells contain simple text values, you can simply build an array of arrays of strings and populate the values from your project's model data, etc.  If the table needs more formatting than that (e.g., paragraphs, images, etc.), then you'll do fundamentally the same thing, except you'll need to configure the data structure as an array of arrays of TableCellModel objects.  

*The row arrays can actually be mixed--some items as strings, some items as TableCellModels, but that's not a super common usage pattern.*

A simple example:

```ruby
# build data structure
tdata  = []
tdata << ['First Name', 'Last Name', 'Email']
User.order(:first_name, :last_name).each do |u|
  tdata << [u.first_name, u.last_name, u.email]
end

# add table to document
docx.table tdata
```

Ultimately, it's helpful to keep in mind that Caracal is just Ruby.  There's no magic happening.  Caracal simply parses your commands into models and then uses those models to render XML output (which is all a Word document really is).

The only "trick" to Caracal is that it generally can't preserve the view context for long, so unless you're an advanced rubyist, I always recommend sending Caracal functions arguments that have already been put in the local scope (like the example above).

**Comment by istiaqiut** [comment]
Hi @jdugan 
Thanks for your answer.
Sorry again for disturbing you. I know this is another issue.

I am trying to add a background image on a page.
I am trying following ways.
data = Base64.encode64(File.read('public/short_pic.png'))
docx.h1 'Introduction', background: data,  width: 450, height: 600 
or
docx.h1 'Introduction', background: img data,  width: 450, height: 600

**Comment by jdugan** [comment]
This isn't valid syntax.  There is no `:background` option for any heading (or paragraph-like) tag.  You can set a background color (which functions like highlighting the text) through the `:bgcolor` option, but there is currently no way to set a background image.

#### A couple notes:

1. The documentation in the README is exhaustive.  If you don't see an option there, it does not exist.  Caracal does not understand the entire HTML spec, just a small subset to facilitate common Word tasks.  Sending Caracal options it does not recognise will result in errors 100% of the time.

2.  If you want to ask about a new feature, please open a new issue.  As things stand, this issue&mdash;which is theoretically about naming column headers&mdash;now includes dissociated commentary about background images.  This makes information harder for new users to find.
