### ISSUE TITLE
paragraph or text use in tablecell model

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#77]
Hello,
Can text format be used in TableCellModel?
For example:
c2 = Caracal::Core::Models::TableCellModel.new  do
p 'Name: ',  bold: true,
end
This can be done.
 Can this be possible in one line-
c2 = Caracal::Core::Models::TableCellModel.new  do
p 'Name: ',  bold: true, '    ', ' Age'
end
Only the Name would be bold.

Thanks

**Comment by jdugan** [comment]
You sure can.  The syntax is different from what you propose, but the functionality is the same.

Please see the documentation in the README [here](https://github.com/trade-informatics/caracal/blob/master/README.md#paragraphs).  The second code section shows how you can call lower-level Caracal commands inside a `p` block.
