### ISSUE TITLE
iframe can not load its own property

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#79]
Hello
I am trying to load file external docx file via following command
docx.iframe data: File.read('public/snippet.docx')
The problem is that in that file the font is 'Times New Roman' which is not rendering in my newly created docx file. It generates in the 'Arial' format which is default in caracal gem.

**Comment by jdugan** [comment]
### Diagnosis

I am of course guessing, given how little information I have, but I suspect the snippet actually uses that document's standard font styles (normal, heading1, etc.), which would explain why it adopts the Caracal default styles of the same name.

The way the `iframe` tag works is conceptually similar to taking the contents of one HTML page's `<body/>` tag and appending them to another HTML document's `<body/>` tag.  All the stylesheet information from the first page would be lost and the snippet would take on the stylesheet characteristics of the second page.

### Solutions (?)

If you want the whole Caracal document to be TNR, you could simple set the font to that.

If you need the snippet to be different than the outer document, you'll need to figure out a way to either 
(a) create the snippet with custom styles and then recreate those in Caracal, or 
(b) set the default font to TNR (to affect the snippet content) and then create a set of custom Caracal styles for the content generated in the outer document.  

*Full disclosure: I've never done either of those strategies, so I'm not certain they would work.*

**Comment by istiaqiut** [comment]
Hi @jdugan ,
I am considering the first solution. Can you give an idea of recreating custom style in Caracal?

Thanks

**Comment by jdugan** [comment]
The README details how to define and use text styles.
