### ISSUE TITLE
font size problem

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#80]
Hi again,
When I am retrieving paragraph from database, the font size is not working. 
For example in the table, in one column the data is saved into two paragraphs, If I define the font size 18 for that column, the font size is default for the first paragraph, for the second paragraph the font size is correct.
docx.p user.biography, size: 18

Here the biography has two paragraphs. While retrieving in the document, the first font size is default (10) and for the second paragraph the font size in 9.

Thanks

**Comment by jdugan** [comment]
What does `user.biography` contain?  Text and line feeds?  Is there any markup in the field value?

**Comment by istiaqiut** [comment]
Only text.

**Comment by jdugan** [comment]
Assuming the value is a text string with `\n`s to create separate paragraphs, there's nothing in the Caracal programming&mdash;to my knowledge&mdash;that would cause this to happen.  Caracal never evaluates the content passed to its commands&mdash;it simply parrots everything back out in the OOXML.  Word, of course, might have an issue with the content, but that's not really a Caracal concern per se.
 
Have you inspected the OOXML in the output file?  Does the markup in the document.xml file match what the document renderer produces?

If that's not illuminating, another strategy might be to use ruby to `.split` the biography into an array of paragraph texts and call docx.p for each item in the resulting array.  That might circumvent whatever formatting issue Word has with the text in the biography.

**Comment by istiaqiut** [comment]
Hi @jdugan 
Thanks for the answer.

**Comment by istiaqiut** [comment]
Hi @jdugan 
Just asking-
When is the next update?

Thanks
