### ISSUE TITLE
text and image in same line

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#81]
Hi @jdugan 
Facing a problem,
I am trying to place image and text on the same line but the text is placed on the next line. Is there a way?

Thanks & Happy New Year

**Comment by jdugan** [comment]
For right now, you can use a table with no border to accomplish this.  

If [Issue 31](https://github.com/trade-informatics/caracal/issues/31) is ever resolved, using a floating image would also work.
