### ISSUE TITLE
Multilene paragraph styling doesn't work

### ISSUE THREAD

**Issue by bolshakov** [trade-informatics/caracal#89]
I'm trying to apply style to paragraph with two lines:

```ruby
Caracal::Document.save 'example.docx' do |docx|
  docx.p(bold: true) do
    text('first line')
    br
    text('second line')
  end
end
```

But rendered text is not bold.

**Comment by jdugan** [comment]
This isn't valid Caracal syntax.  Caracal expects:

```ruby
Caracal::Document.save 'example.docx' do |docx|
  docx.p do
    text('first line', bold: true)
    br
    text('second line', bold: true)
  end
end
```

Caracal only accepts attributes at the paragraph level when the content is a simple string.  It is, in that case, effectively proxying the attributes onto the single TextModel it creates to house the simple string.

If you use the more granular block syntax, each `text` command must be styled individually.  If you find your repeating attribute groupings, you might be better off defining a custom style and then apply that to each `text` command.

**Comment by bolshakov** [comment]
Thank you for explanation!

**Comment by jdugan** [comment]
Of course.  Thanks for using Caracal!

FWIW, the library probably **_should_** take paragraph-level styling.  I believe Word does, in fact, work like that under the hood.  

But Caracal was originally written under a project deadline, so it cuts a few corners here and there in the interest of simplifying the codebase. :)
