### ISSUE TITLE
Do you know how to convert line height to relative units?

### ISSUE THREAD

**Issue by bolshakov** [trade-informatics/caracal#91]
In text editor you set line spacing as relative units -- 1, 1.5, 2, etc but in caracal the only option is to set line height in twips. I assume it should some how depends on font size (in half points).

Do you know how to convert font size to line hight if I know font size and relative line spacing?

**Comment by jdugan** [comment]
I know, it's not exactly intuitive.  It's covered in the README [here](https://github.com/trade-informatics/caracal#units).  Note the apology in the text! :)

**Comment by bolshakov** [comment]
@jdugan I've seen this section and understand what are twips and half points. But the question is in what units measured line spacing? As I understand, line spacing is not line height, right? 

I have to convert business requirement (make line spacing 1.5) to line height in twips. Any idea?

**Comment by jdugan** [comment]
Ah, sorry.  I misunderstood your question.  

Right now, line height isn't adjustable on individual text runs, only at the custom style level via the `line` attribute.  If you want the line spacing to be a certain value by default, the easiest thing to do is to override the [default styles](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/core/styles.rb#L19) accordingly.  If you create a custom style with the same ID as a default style, you'll override it.

In terms of calculation, you'd set line to `font_size_pts * 20 * factor`.  So, if the current font size is `12pt` and you want `1.5` spacing, you'd do `12 * 20 * 1.5` to yield a `line` value of `360` (twips).

**Note**: I presume OOXML allows line settings at the run level, so that might be easy to patch into the library by adding a new attribute to the paragraph and text models and the corresponding XML attribute to the document renderer.

**Comment by bolshakov** [comment]
That was my first thought. But unfortunately `font_size_pts * 20 * factor` formula does not work.  For example if you set line height to 1.5 this way `font_size_pts * 20 * 1.5` the actual line spacing in document will be 1.3, not 1.5. 

I've done some calculations and the formula should be `font_size_phs * 24 * factor` 

[This document](https://github.com/trade-informatics/caracal/files/1859599/example.docx) demonstrates relation between line hight and line spacing. 

@jdugan thanks for support, I really appreciate your work!

**Comment by bolshakov** [comment]
It looks like  I was wrong. Line spacing doesn't depend on font size at all. I dug into "ECMA-376, Second Edition, Part 1 - Fundamentals And Markup Language Reference" and it states the following about `<w:spacing w:line="xxx" />` element.


> This attribute specifies the amount of vertical spacing between lines of text within this paragraph.
If this element is omitted on a given paragraph, its value is determined by the setting previously set at any level of the style hierarchy (i.e. that previous setting remains unchanged). If this setting is never specified in the style hierarchy, then no line spacing shall be applied to lines within this paragraph.
>
> If the value of the lineRule attribute is either atLeast or exactly, then the value of this attribute shall be interpreted as twentieths of a point. When the value of the lineRule attribute is either exactly, the text shall be positioned as follows within that line height:
> 
> * When the line height is too small, the text shall be positioned at the bottom of the line (i.e. clipped from the top down)
> * When the line height is too large, the text shall be centered in the available space.
>
> If the value of the lineRule attribute is auto, then the value of the line attribute shall be interpreted as 240ths of a line, in the manner described by the simple type's values.
> 
> [Example: Consider the following WordprocessingML paragraph which should have an inter-line spacing of 1.15 times the line height. This constraint would be specified using the following WordprocessingML:
>
> ```xml
> <w:pPr>
>    <w:spacing w:line="276" w:lineRule="auto" />
> </w:pPr>
> ```
>
> The lineRule attribute value of auto specifies that the value of the line attribute is to be interpreted in 240ths of a single line height, which means that the net spacing is 276/240ths of a line or 1.15 lines tall. end example]
>

Thus, since our default paragraph style has `w:lineRule="auto"` set: 

```xml
<w:docDefaults>
    <w:pPrDefault>
      <w:pPr>
        <w:spacing w:lineRule="auto" w:before="0" w:after="0" w:line="320"/>
      </w:pPr>
    </w:pPrDefault>
</w:docDefaults>
```

and this value inherited by all styles, to calculate relative line spacing you have to use the following equation: `line_height = 240ths * factor`.

* Line spacing 1 is 240ths
* Line spacing 1.5 is 360ths
* Line spacing 2 is 482ths
* etc.
