### ISSUE TITLE
Can't use vars rather than string literals inside `p` blocks?

### ISSUE THREAD

**Issue by patrick-gleeson** [trade-informatics/caracal#92]
I am almost certainly being stupid here, but I am currently stumped so thought it would be good to see if I have indeed hit a limitation of the tool.

I want to do something like the following:

```ruby
class SomeExcitingEntity
  def initialize(content)
    @content = content
  end

  def render(docx)
    docx.p do
      text 'The content of this exciting entity is: '
      text @content, font: 'Courier New'
    end
  end
end
```

The problem is that `@content` is an ivar on the instance of SomeExcitingEntity. However, once inside the `doxc#p` block, because you're using `instance_eval`, we're evaluating the code from inside an instance of `Caracal::Core::Models::TextModel`. This means that from inside the block I have no access to `@content`. So what gets rendered is just "The content of this exciting entity is: ".

Is there any way I can access the attributes and methods of the calling object from inside a `.p` block?

**Comment by patrick-gleeson** [comment]
Never mind, I got there in the end:

```ruby
class SomeExcitingEntity
  def initialize(content)
    @content = content
  end

  def render(docx)
    docx.p do |context|
      context.text 'The content of this exciting entity is: '
      context.text @content, font: 'Courier New'
    end
  end
end
```

**Comment by jdugan** [comment]
Yeah, lexical scoping can be a tough nut to crack with this library.  

FWIW, I think you could have also solved the issue by localising the string content to a method variable.  Generally speaking, as long as the variables you use in the Caracal block are plain ruby objects, they can be passed around with impunity.

But your solution is what I would consider the better method in this case.  :)
