### ISSUE TITLE
Ability to add/insert bookmarks

### ISSUE THREAD

**Issue by prajakta-webonise** [trade-informatics/caracal#98]
Hello team,

I need a feature which will allow me to insert bookmarks in a word document.

**Comment by jdugan** [comment]
Hi, Prajakta.

There's no team per se.  Caracal is a library I wrote for a project some years ago that other people continue to find useful.  I sometimes add a trivial feature here or there if I can do so in a single sit-down, but that's pretty uncommon at this point.  Anything Caracal lacks is not likely to be trivial to implement.

Caracal is essentially an exercise in reverse engineering the OOXML that underpins a Word document ([see here](https://github.com/trade-informatics/caracal#how-to-work-on-a-problem)) and then following along with the design and style conventions of the project.  

If you need guidance on that work, I'm happy to answer any questions you have.

**Comment by rmarone** [comment]
Had a similar need, so I submitted this pull request with an implementation

**Comment by jdugan** [comment]
Thanks again @rmarone.
